name: Precommit
description: "Run any present pre-commit configuration in CI pipeline."
author: "Claus-Theodor Riegg"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
            mkdir -p terraform-docs
            cd terraform-docs
            curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.20.0/terraform-docs-v0.20.0-$(uname)-amd64.tar.gz
            tar -xzf terraform-docs.tar.gz
            chmod +x terraform-docs
            sudo mv terraform-docs /usr/bin/terraform-docs
            curl -sSLo ./tofu.tar.gz https://github.com/opentofu/opentofu/releases/download/v1.9.1/tofu_1.9.1_$(uname)_amd64.tar.gz
            tar -xzf tofu.tar.gz
            chmod +x tofu
            sudo mv tofu /usr/bin/tofu
      shell: bash
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
